services:
  backend:
    image: download-backend:latest
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT_INTERNAL}"
    environment:
      PORT: ${BACKEND_PORT_INTERNAL}
      FRONTEND_URL: ${FRONTEND_URL}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  frontend:
    image: download-frontend:latest
    ports:
      - ${FRONTEND_PORT}:5173
    environment:
      VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}

  db:
    image: postgres
    restart: always
    environment: [POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
